spring:
  application:
    name: yasisolutions
    admin:
      enabled: true
  build:
    version: '@project.version' #picks up project version in pom file
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/yasi_solutions?loggerlevel=OFF
    username: postgres
    password: jess88
    hikari:
      data-source-properties.stringtype: unspecified
      maximum-pool-size: 25
      connection-timeout: 6000

    jpa:
      show-sql: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:yasi-logback.xml
  level:
    root:
      org:
        springframework:
          jdbc:
            core:
              JdbcTemplate: debug
          security: debug
  file:
    path: /var/log/app_logs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

